apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
  params:
    - name: image-url
      value: anchorlau/budget-app:latest