apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: 34.70.242.19:5000/budget-app_web:latest  # Replace with your image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: rails-app