apiVersion: v1
kind: Secret
metadata:
  name: private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/heibais1986/Budget-App.git  # Replace with your repo URL
  password: 324866llb  # Replace with your GitHub personal access token
  username: 18032926002@139.com  # Replace with your GitHub username